/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as LineAppImport } from './routes/line-app'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as ForbiddenImport } from './routes/Forbidden'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedVehiclesImport } from './routes/_authenticated/vehicles'
import { Route as AuthenticatedSaffImport } from './routes/_authenticated/saff'
import { Route as AuthenticatedResidentsImport } from './routes/_authenticated/residents'
import { Route as AuthenticatedInvitationsImport } from './routes/_authenticated/invitations'
import { Route as AuthenticatedHistoryInOutImport } from './routes/_authenticated/history-in-out'
import { Route as AuthenticatedDashboardImport } from './routes/_authenticated/dashboard'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LineAppRoute = LineAppImport.update({
  id: '/line-app',
  path: '/line-app',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const ForbiddenRoute = ForbiddenImport.update({
  id: '/Forbidden',
  path: '/Forbidden',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedVehiclesRoute = AuthenticatedVehiclesImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedSaffRoute = AuthenticatedSaffImport.update({
  id: '/saff',
  path: '/saff',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedResidentsRoute = AuthenticatedResidentsImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedInvitationsRoute = AuthenticatedInvitationsImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedHistoryInOutRoute = AuthenticatedHistoryInOutImport.update({
  id: '/history-in-out',
  path: '/history-in-out',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Forbidden': {
      id: '/Forbidden'
      path: '/Forbidden'
      fullPath: '/Forbidden'
      preLoaderRoute: typeof ForbiddenImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/line-app': {
      id: '/line-app'
      path: '/line-app'
      fullPath: '/line-app'
      preLoaderRoute: typeof LineAppImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/history-in-out': {
      id: '/_authenticated/history-in-out'
      path: '/history-in-out'
      fullPath: '/history-in-out'
      preLoaderRoute: typeof AuthenticatedHistoryInOutImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/invitations': {
      id: '/_authenticated/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof AuthenticatedInvitationsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/residents': {
      id: '/_authenticated/residents'
      path: '/residents'
      fullPath: '/residents'
      preLoaderRoute: typeof AuthenticatedResidentsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/saff': {
      id: '/_authenticated/saff'
      path: '/saff'
      fullPath: '/saff'
      preLoaderRoute: typeof AuthenticatedSaffImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/vehicles': {
      id: '/_authenticated/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthenticatedVehiclesImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryInOutRoute: typeof AuthenticatedHistoryInOutRoute
  AuthenticatedInvitationsRoute: typeof AuthenticatedInvitationsRoute
  AuthenticatedResidentsRoute: typeof AuthenticatedResidentsRoute
  AuthenticatedSaffRoute: typeof AuthenticatedSaffRoute
  AuthenticatedVehiclesRoute: typeof AuthenticatedVehiclesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryInOutRoute: AuthenticatedHistoryInOutRoute,
  AuthenticatedInvitationsRoute: AuthenticatedInvitationsRoute,
  AuthenticatedResidentsRoute: AuthenticatedResidentsRoute,
  AuthenticatedSaffRoute: AuthenticatedSaffRoute,
  AuthenticatedVehiclesRoute: AuthenticatedVehiclesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Forbidden': typeof ForbiddenRoute
  '': typeof AuthenticatedRouteWithChildren
  '/line-app': typeof LineAppRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history-in-out': typeof AuthenticatedHistoryInOutRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/residents': typeof AuthenticatedResidentsRoute
  '/saff': typeof AuthenticatedSaffRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Forbidden': typeof ForbiddenRoute
  '': typeof AuthenticatedRouteWithChildren
  '/line-app': typeof LineAppRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history-in-out': typeof AuthenticatedHistoryInOutRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/residents': typeof AuthenticatedResidentsRoute
  '/saff': typeof AuthenticatedSaffRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Forbidden': typeof ForbiddenRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/line-app': typeof LineAppRoute
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history-in-out': typeof AuthenticatedHistoryInOutRoute
  '/_authenticated/invitations': typeof AuthenticatedInvitationsRoute
  '/_authenticated/residents': typeof AuthenticatedResidentsRoute
  '/_authenticated/saff': typeof AuthenticatedSaffRoute
  '/_authenticated/vehicles': typeof AuthenticatedVehiclesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Forbidden'
    | ''
    | '/line-app'
    | '/login'
    | '/dashboard'
    | '/history-in-out'
    | '/invitations'
    | '/residents'
    | '/saff'
    | '/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Forbidden'
    | ''
    | '/line-app'
    | '/login'
    | '/dashboard'
    | '/history-in-out'
    | '/invitations'
    | '/residents'
    | '/saff'
    | '/vehicles'
  id:
    | '__root__'
    | '/'
    | '/Forbidden'
    | '/_authenticated'
    | '/line-app'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/history-in-out'
    | '/_authenticated/invitations'
    | '/_authenticated/residents'
    | '/_authenticated/saff'
    | '/_authenticated/vehicles'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForbiddenRoute: typeof ForbiddenRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LineAppRoute: typeof LineAppRoute
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForbiddenRoute: ForbiddenRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LineAppRoute: LineAppRoute,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Forbidden",
        "/_authenticated",
        "/line-app",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Forbidden": {
      "filePath": "Forbidden.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.ts",
      "children": [
        "/_authenticated/dashboard",
        "/_authenticated/history-in-out",
        "/_authenticated/invitations",
        "/_authenticated/residents",
        "/_authenticated/saff",
        "/_authenticated/vehicles"
      ]
    },
    "/line-app": {
      "filePath": "line-app.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authenticated/dashboard": {
      "filePath": "_authenticated/dashboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/history-in-out": {
      "filePath": "_authenticated/history-in-out.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/invitations": {
      "filePath": "_authenticated/invitations.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/residents": {
      "filePath": "_authenticated/residents.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/saff": {
      "filePath": "_authenticated/saff.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/vehicles": {
      "filePath": "_authenticated/vehicles.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
